dataset_name: 'sceneFun3D'
meshing:
  eval_rec: True
tracking:
  vis_freq: 10
  vis_inside_freq: 5
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: False
  lr: 0.001
  pixels: 200
  iters: 10
mapping:
  every_frame: 5
  vis_freq: 10
  vis_inside_freq: 5
  mesh_freq: 10
  ckpt_freq: 500
  keyframe_every: 10
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1500
  iters: 60
camera_params:
  image_height: 1440
  image_width: 1920
  fx: -1
  fy: -1
  cx: -1
  cy: -1
  png_depth_scale: 1000 #for depth image in png format
  crop_edge: 0
